[variables]
NIXPACKS_PYTHON_VERSION = "3.10"

[phases.setup]
nixPkgs = ["..."]

[phases.install]
cmds = ["cd locallibrary && pip install -r requirements.txt --break-system-packages"]

[phases.build]
cmds = ["cd locallibrary && python manage.py collectstatic --noinput"]

[start]
cmd = "cd locallibrary && gunicorn locallibrary.wsgi --log-file -"
